### ISSUE TITLE
Relation to JSON Schema

### ISSUE THREAD

**Issue by blamario** [LeapYear/aeson-schemas#23]
Are there any plans to support [JSON Schema](https://json-schema.org/)? My impression is not, but either way the answer should be prominently stated in README. Otherwise the similarity of the library name gives false hopes to people like me.

**Comment by brandon-leapyear** [comment]
No, it seems like that would be a whole project by itself.

You're welcome to submit a PR if you want. I would also be open to renaming this project entirely, although that might not be possible with it already being on Hackage under this name

**Comment by MangoIV** [comment]
i agree that this should be stated in the `README`, it's very confusing
