### ISSUE TITLE
Record object would be AWSOME!

### ISSUE THREAD

**Issue by mikesol** [LeapYear/aeson-schemas#24]
Sorry, this isn't a bug report, but the library is _awesome_ and I have one feature request.

Would it be possible to add a record type that parsed an object, ie `Record Int` would be an object where the values were integers.

I can help with implementing it if the idea makes sense - I looked at the code and it looks like it'd be basically the same as `List` with some slight modifications.

**Comment by brandon-leapyear** [comment]
Thanks for using this library! I'm not sure what the benefit of having `Record Int` would be. Why not just use `HashMap Text Int`?

Right now, I don't think the code allows for polymorphic names like that
```hs
{
  foo: HashMap Text Int,
}
```

(which is a good issue to write separately) but you could just make an alias `type IntRecord = HashMap Text Int`?

**Comment by mikesol** [comment]
Ah, I didn't realize that the DSL allowed for any type to be in there - I thought it had to follow the convention of using the types predefined in the library (ie `List`). Thanks for the clarification!

**Comment by brandon-leapyear** [comment]
Yup! It should be documented [here](http://hackage.haskell.org/package/aeson-schemas-1.1.0/docs/Data-Aeson-Schema.html#v:schema). Let me know if it can be improved!
